[build]
  publish = "dist"
  command = "yarn build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--version"
  YARN_VERSION = "1.22.22"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Content-Type = "image/x-icon"

# Redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
